dataset<-read.table("household_power_consumption.txt",sep=";",header = TRUE)
dataset[,1]<-as.Date(dataset[,1],"%d/%m/%Y")
sub<-subset(dataset,Date>="2007-02-01" & Date<="2007-02-02")
sub[,3]<-as.numeric(as.character(sub[,3]))
sub<-cbind(sub,datetime)
Sys.setenv(LANG = 'en')
Sys.setlocale("LC_TIME", "English")
plot(sub$datetime,sub$Global_active_power,type="l",xlab = " ",ylab = "Global Active Power (kilowatts)" )
dev.copy(png,"plot2.png")
dev.off()
